import Head from "next/head";
import styles from "../styles/Home.module.css";

import sanity from "../lib/sanity";

import { useState } from "react";

export async function getServerSideProps() {
  const todos = await sanity.fetch(`*[_type == "Todo"]`);

  return {
    props: {
      todos: todos,
    },
  };
}

export default function Home({ todos }) {
  const [task, setTask] = useState([]);
  const [done, setDone] = useState([]);
  const [dueDate, setDueDate] = useState([]);

  const createTodo = async () => {
    const todo = {
      task: task,
      done: done,
      dueDate: dueDate,
    };

    await fetch("/api/todos", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(todo),
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <label htmlFor="task">Task</label>
        <br />
        <input
          type="text"
          name="task"
          onChange={(e) => setTask(e.target.value)}
        />
        <br />
        <label htmlFor="done">Done ?</label>
        <br />
        <input
          type="checkbox"
          name="done"
          onChange={(e) => setDone(e.target.value)}
        />
        <br />
        <label htmlFor="date">Date</label>
        <br />
        <input
          type="date"
          name="date"
          onChange={(e) => setDueDate(e.target.value)}
        />
        <br />
        <button onClick={() => createTodo()}>Create</button>
        {todos.map((todo) => (
          <div key={todo._id}>
            <h1>{todo.Task}</h1>
            <p>{todo.Done ? "Done" : "Not Done"}</p>
            <p>{todo.DueDate}</p>
          </div>
        ))}
      </main>
    </div>
  );
}
